### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by thapapratyush** [InterviewBae/InterviewBae#2]
Current commit does not run with the undefined React error.

Details:
_Packages and versions_
+ body-parser@1.18.3
+ express@4.16.4
+ passport-jwt@4.0.0
+ jsonwebtoken@8.5.1
+ passport@0.4.0
+ is-empty@1.2.0
+ bcryptjs@2.4.3
+ mongoose@5.4.21
+ validator@10.11.0
+ concurrently@4.1.0

Error thrown at:
node_modules/redux/es/redux.js:575
   572 | 
   573 |   return funcs.reduce(function (a, b) {
   574 |     return function () {
> 575 |       return a(b.apply(void 0, arguments));
   576 |     };
   577 |   });
   578 | }

which was invoked by:
src/store.js:9
    6 | 
    7 | const middleware = [thunk];
    8 | 
>  9 | const store = createStore(
   10 |   rootReducer,
   11 |   initialState,
   12 |   compose(

Might be a weird webpack or a quirky compatibility issue. Assigning myself to explore more

**Comment by rajjwal** [comment]
Get react developer tools and redux developer tools. 

More in here: https://github.com/reduxjs/redux/issues/2359

**Comment by rajjwal** [comment]
Babu muji!

**Comment by thapapratyush** [comment]
Updated Readme
